---
path: github.com/OwnLocal/rv
deps:
  - loc: github.com/gocraft/web

  - loc: https://github.com/onsi/ginkgo.git
    type: git
    ref: 291f28e66dd277f35d3635990a7448759645c7e7
    path: github.com/onsi/ginkgo

  - loc: https://github.com/onsi/gomega.git
    type: git
    ref: 8adf9e1730c55cdc590de7d49766cb2acc88d8f2
    path: github.com/onsi/gomega

  - loc: github.com/onsi/ginkgo/ginkgo

